# Generated by Django 4.1.7 on 2023-03-10 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bapz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=120)),
                ('price', models.TextField()),
                ('color', models.TextField()),
                ('size', models.TextField()),
            ],
        ),
    ]
